// 게임 전역 가변 상태. 모듈 사이에서 공유되는 값은 모두 여기에 모은다.
// 타입은 점진적으로 붙인다(지금은 PoC에서 옮겨온 구조 그대로).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const $: any = {
  solids: [],
  WORLD: 4700,
  GOAL: 3600,
  clueSpots: [],
  ENEMY_DEF: [],
  CKS: [],
  clues: undefined,
  enemies: undefined,
  fx: undefined,
  pops: undefined,
  hp: undefined,
  overT: undefined,
  sword: undefined,
  orbs: undefined,
  waves: undefined,
  freeze: 0,
  prevSlash: false,
  ARENA: {
    k: 'rat',
    x0: 3740,
    x1: 4700,
    active: false,
    done: false,
    title: 0,
  },
  CKPT: -1,
  shake: 0,
  swaves: [],
  ckX: -1,
  eproj: [],
  strikes: [],
  parrows: [],
  alarmT: 0,
  pHist: [],
  mode: 'intro',
  IN: null,
  STAGE: 0,
  DIFF: 1,
  stageSnap: null,
  memTotal: 0,
  SND: {
    on: true,
  },
  menuSel: 0,
  jumpPressedAt: -1,
  debug: false,
  p: undefined,
  t: 0,
  cam: 0,
  done: false,
  lastSafe: undefined,
  ESPR: {},
  lastR: performance.now(),
  SPR: undefined,
};
